name: Run Bot

on:
  push:
    branches:
      - '*'

jobs:
  run_bot:
    name: Run Bot
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Discord.py
        run: pip3 install discord.py

      - name: Run Bot
        run: echo 1
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Restart Bot
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_TOKEN }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
