name: Restart Workflow
on:
  repository_dispatch:
    types: [restart]

jobs:
  restart_job:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Workflow
        run: |
          URL=https://api.github.com/repos/${{github.repository}}/actions/runs/${{ github.event.client_payload.runid }}/rerun
          curl -X POST -u "weide-zhou:${{secrets.TEST_TOKEN}}" $URL
